tipo=input("Digite o que quiser: ")
print ('o tipo é: {}'.format (type (tipo)))
print ('é tudo maiusculo? {}'.format(tipo.isupper()))
print ('é tudo espaço? {}'.format(tipo.isspace()))
print ('é um numero ou letra? {}'.format(tipo.isalnum()))
print ('é tudo letra? {}'.format(tipo.isalpha()))
print ('é tudo minusculo? {}'.format(tipo.islower()))
print ('é decimal?', tipo.isdecimal())
